### ISSUE TITLE
Error on none-admin-user

### ISSUE THREAD

**Issue by Finulin** [Epixskill/recent-content-widget#1] opened 2022-08-05 15:43 UTC
for user with none admin-rights, shows the widget only an error-message

**Comment by Epixskill** [comment] 2022-08-06 16:34
Can you give some more information on the issue like which TYPO3 and php version you are using as well as some more precise information on the error message itself?

**Comment by DL1ndner** [comment] 2023-04-11 12:10
I can confirm this issue on TYPO3 11.5.25 with PHP 7.4. The error shown is (in German):

"Beim Abrufen der Informationen für dieses Widget ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut und wenn das Problem weiterhin auftritt, kontaktieren Sie Ihren Administrator."

The corresponding TYPO3 error is:

"Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1578950324: The given page record is invalid. Missing uid. \| RuntimeException thrown in file /PATH_TO_SRC/typo3_src-11.5.25/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php in line 345. Requested URL: XYZ/typo3/ajax/dashboard/widget/content?token=--AnonymizedToken--&widget=recentContent"

Thank you!

**Comment by Epixskill** [comment] 2023-04-20 17:43
@DL1ndner I created a new release v1.1.2 that should address this bug. Now, the widget considers only content element with a pid greater than 0. 
Can you confirm that the issue is fixed in the new version?

**Comment by DL1ndner** [comment] 2023-04-21 06:51
V 1.1.2 does not change behaviour, same error message is showing, also on PHP 8.1. Do I have to set uid somewhere? I couldn't find any config.

**Comment by DL1ndner** [comment] 2023-04-27 17:47
Sorry, I checked again and now it works (for some reason extension update failed before). 
Thank you!!

**Comment by Epixskill** [comment] 2023-04-27 19:44
Glad to hear that!

**Closed as completed by Epixskill** 2023-04-27 19:44 UTC
